### ISSUE TITLE
Failed To Join Server, Status Code: 400

### ISSUE THREAD

**Issue by augis01** [natrixdev/Discord-Server-Boost-Botter#19]
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x03CF5928>
Traceback (most recent call last):
  File "C:\Users\augus\AppData\Local\Programs\Python\Python38-32\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\augus\AppData\Local\Programs\Python\Python38-32\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\augus\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 711, in call_soon
    self._check_closed()
  File "C:\Users\augus\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 504, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by natrixdev** [comment]
Try to use your own tokens, install last python version and if it still not working dm me on Discord (natrix#4526).
